// Generated by CoffeeScript 1.9.3
var Speaker, StreamPlayer, audioOptions, events, lame, queue, request, self, trackInfo,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Speaker = require('speaker');

lame = require('lame');

request = require('request');

events = require('events');

queue = [];

trackInfo = [];

self = null;

audioOptions = {
  channels: 2,
  bitDepth: 16,
  sampleRate: 44100,
  mode: lame.STEREO
};

StreamPlayer = (function(superClass) {
  extend(StreamPlayer, superClass);

  function StreamPlayer() {
    events.EventEmitter.call(this);
    self = this;
  }

  StreamPlayer.prototype.play = function() {
    var nextSongUrl;
    nextSongUrl = queue[0];
    if (typeof nextSongUrl !== 'undefined') {
      return self.getStream(nextSongUrl, self.playStream);
    } else {
      return new Error('The queue is empty.');
    }
  };

  StreamPlayer.prototype.add = function(url, track) {
    queue.push(url);
    trackInfo.push(track);
    return self.emit('song added');
  };

  StreamPlayer.prototype.nowPlaying = function() {
    return trackInfo[0];
  };

  StreamPlayer.prototype.getStream = function(url, callback) {
    return request.get(url).on('response', function(res) {
      return callback(res);
    });
  };

  StreamPlayer.prototype.playStream = function(stream) {
    var decoder, speaker;
    decoder = new lame.Decoder();
    speaker = new Speaker(audioOptions);
    return stream.pipe(decoder).once('format', function() {
      this.pipe(speaker);
      self.emit('play start');
      return speaker.once('close', function() {
        self.emit('play end');
        queue.shift();
        trackInfo.shift();
        return self.play();
      });
    });
  };

  return StreamPlayer;

})(events.EventEmitter);

module.exports = StreamPlayer;
